name: "Tests"

on:
  - "push"
  - "pull_request"

jobs:
  rake:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "jruby-9.2.19.0"
          - "truffleruby-22.3.0"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby_version }}"
          bundler-cache: true
      - run: "bundle exec rake"
