name: "Tests"

on:
  - "push"
  - "pull_request"

jobs:
  rake:
    runs-on: "ubuntu-latest"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "2.3.8"
          - "2.4.5"
          - "2.5.3"
          - "2.6.3"
          - "2.7.2"
          - "jruby-9.2.19.0"
          - "truffleruby-21.1.0"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "${{ matrix.ruby_version }}"
      - run: "bundle install"
      - run: "bundle exec rake"
